### ISSUE TITLE
Authorization no longer works

### ISSUE THREAD

**Issue by gargargarrick** [markdoliner/flickrmirrorer#4]
I have the latest version of the script from the repository, flickrapi 2.0, and Python 2.7.9. If I try to run flickrmirrorer, the backup fails and I get a "too many values to unpack" error on line 135. The value returned for self.flickr.get_token_part_one(perms='read') is: `{"stat":"fail","code":112,"message":"Method \"flickr.get.token.part.one\" not found"}`. I did some digging and it seems that get_token_part_one and part_two were recently deprecated in favor of authenticate_via_browser and OAuth.
I made a cursory effort to fork flickrmirrorer to use the newer method, but (not having much experience with APIs) my efforts yielded nothing but 401 errors.
Any advice would be appreciated, and thanks for all your work on flickrmirrorer!

**Comment by markdoliner** [comment]
Hi gargargarrick! Thanks for mentioning this. I had some free time today so I took a stab at this. It turns out the script still worked with older versions of the python flickrapi library. It didn't work with flickrapi 2.0, as you know.

I'm not sure why you were getting 401 errors. I saw 401 a few times while updating the code to work with the new flickrapi. Seems like maybe the flickrapi auth code doesn't like it when you reuse a flickr object and request auth multiple times.

Anyhoo, I think I got everything working. I made some other changes. I just pushed the changes to GitHub. Please let me know if you find any other problems. Thanks!
